<a href="https://colab.research.google.com/github/Satyamaadi/Algorithms/blob/main/Data_Analytics_3_Pandasindepth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
frame = pd.DataFrame({'id':['A','B','C','D','E'],'price':[11,12,13,14,15]})

In [4]:
frame

  id  price
0  A     11
1  B     12
2  C     13
3  D     14
4  E     15

In [7]:
frame2 = pd.DataFrame( {'id': ['A','B','C','D'],
                        'color':['white','red','red','black']})
frame2

  id  color
0  A  white
1  B    red
2  C    red
3  D  black

In [8]:
pd.merge(frame,frame2)

  id  price  color
0  A     11  white
1  B     12    red
2  C     13    red
3  D     14  black

We can also give arg -> on = 'Column name' in merge() , it can be either a list or individual features

In [9]:
frame1 = pd.DataFrame( {'id': ['ball','pencil','pen',',mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','PPOD']})
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})
frame2
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3     ,mug  black   POD
4  ashtray  green  PPOD

In [12]:
pd.merge(frame1,frame2,on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [16]:
pd.merge(frame1,frame2,left_on='id',right_on='brand')

Empty DataFrame
Columns: [id_x, color, brand_x, id_y, brand_y]
Index: []

In [17]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
array2 = np.arange(9).reshape((3,3))
array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.concatenate([array1,array2],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
a = pd.Series(np.random.rand(4))

In [24]:
b = pd.Series(np.random.rand(4))

In [25]:
pd.concat([a,b])

0    0.501521
1    0.212832
2    0.282514
3    0.961076
0    0.921585
1    0.150975
2    0.030543
3    0.559410
dtype: float64